# Generated by Django 3.2.7 on 2021-10-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(default='', max_length=8, unique=True)),
                ('book_name', models.CharField(default='', max_length=20)),
                ('book_desc', models.CharField(default='', max_length=100)),
                ('book_author', models.CharField(default='', max_length=20)),
                ('borrowed', models.BooleanField(default=False)),
            ],
        ),
    ]
